<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Week 24 Lab</h1>
</div>


In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part 1 - Python Problems
<hr>

### Exercise 1

Create a function that takes a list of integers and calculates the mean. Use the following formula for calculating averages and not any `mean`/`average` method.

$$ \mu = {\frac {1}{n}}\sum _{i=1}^{n}a_{i}={\frac {a_{1}+a_{2}+\cdots +a_{n}}{n}}$$

In [83]:
example_list = [1,2,3,4,5,6,7,8,9]

def solution(example_list):
    num = np.array(example_list).mean()
    return num

solution(example_list)

5.0

### Exercise 2

Create a class that operates like a stack.  

In [84]:
class Stack:
    def __init__(self):
        self.inserts = []

    def push(self, inserts):
        self.inserts.append(inserts)
        
    def pop(self):
        self.inserts.pop()

test = Stack()
test.push('a')
test.push('b')
test.push('c')
print(test.inserts)
test.pop()
print(test.inserts)

['a', 'b', 'c']
['a', 'b']


### Exercise 3

Write a generator function which returns a few values and then use it to retrieve a value using `next` (the global function). 

In [85]:
def generator():
    out = 0
    yield out

    out += 1
    yield out

    out += 2
    yield out
    
for item in generator():
    print(item)

0
1
3


In [86]:
x = generator()
next(x)

0

### Exercise 4

Create a namedtuple `'Point'` that contains the points `x` and `y`.

In [87]:
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])

In [88]:
a = Point(7,8)
b = Point(9,10)

In [89]:
print(a.x, a.y)
print(b)

7 8
Point(x=9, y=10)


### Exercise 5

Create a moving average class that:
* has a method `add` that is used to add new values
* has a method `avg` that calculates the average of the 5 most recently added values
* has an attribute `values` that contain all values added
* has an attribute `window` that contains the 5 most recently added values

In [92]:
class MovingAverage:
    def __init__(self,values = [], window = []):
        self.values = values
        self.window = window
        
    def __add__(self,value):
        self.values.append(value)
        if len(self.values) >= 5:
            self.window = self.values[-5:]
        else:
             self.window = self.values
        
    def __avg__(self):
        if len(self.values) >= 5:
            self.window = self.values[-5:]
            return sum(self.window) / 5
        return sum(self.values) / len(self.values)

avg = MovingAverage()
avg.__add__(20)
avg.__add__(16)
avg.__add__(234)
avg.__add__(34)
avg.__add__(28)
print(avg.values)
print(avg.window)
avg.__avg__()

[20, 16, 234, 34, 28]
[20, 16, 234, 34, 28]


66.4

## Part 2 - Numpy Problems
<hr>

### Exercise 1

Using numpy, create an array that contains the values of $y$ for each of the $x$ values ranging from 0 to 100.

$$ y = 12x+4  $$

In [93]:
x = np.arange(101)
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [96]:
y = 12*x+4
print(y)

[   4   16   28   40   52   64   76   88  100  112  124  136  148  160
  172  184  196  208  220  232  244  256  268  280  292  304  316  328
  340  352  364  376  388  400  412  424  436  448  460  472  484  496
  508  520  532  544  556  568  580  592  604  616  628  640  652  664
  676  688  700  712  724  736  748  760  772  784  796  808  820  832
  844  856  868  880  892  904  916  928  940  952  964  976  988 1000
 1012 1024 1036 1048 1060 1072 1084 1096 1108 1120 1132 1144 1156 1168
 1180 1192 1204]


### Exercise 2

Create a 2-dimensional numpy array that contains the numbers from 1 to 20 with even numbers in the first column and odd numbers in the second.

In [110]:
arr = np.arange(1, 21).reshape(10, 2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### Exercise 3

Create a numpy array with random numbers between 0 and 1.

In [111]:
np.random.rand(10)

array([0.38422415, 0.15719019, 0.09704368, 0.55061524, 0.91590978,
       0.29168893, 0.12239557, 0.70324051, 0.30348458, 0.46435232])

### Exercise 4

Create an array that contains 100 numbers. All of them between 0 and 5. Then add that to an array that contains the numbers from 0 to 99.

In [112]:
x = np.linspace(0, 5, num=100)
x

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [77]:
y = np.arange(100)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
z = x + y
z

array([  0.        ,   1.05050505,   2.1010101 ,   3.15151515,
         4.2020202 ,   5.25252525,   6.3030303 ,   7.35353535,
         8.4040404 ,   9.45454545,  10.50505051,  11.55555556,
        12.60606061,  13.65656566,  14.70707071,  15.75757576,
        16.80808081,  17.85858586,  18.90909091,  19.95959596,
        21.01010101,  22.06060606,  23.11111111,  24.16161616,
        25.21212121,  26.26262626,  27.31313131,  28.36363636,
        29.41414141,  30.46464646,  31.51515152,  32.56565657,
        33.61616162,  34.66666667,  35.71717172,  36.76767677,
        37.81818182,  38.86868687,  39.91919192,  40.96969697,
        42.02020202,  43.07070707,  44.12121212,  45.17171717,
        46.22222222,  47.27272727,  48.32323232,  49.37373737,
        50.42424242,  51.47474747,  52.52525253,  53.57575758,
        54.62626263,  55.67676768,  56.72727273,  57.77777778,
        58.82828283,  59.87878788,  60.92929293,  61.97979798,
        63.03030303,  64.08080808,  65.13131313,  66.18

### Exercise 5

Create a 10 by 10 matrix containing zeros. Then create a 10 by 10 matrix containing ones. Combine the two matrices so that the new dimensions are 20 by 10.

In [79]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
y = np.ones((10,10))
y

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [81]:
z = np.concatenate((x, y))
z 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 6

Given the following numpy array, find the cumulative sum along the rows. Then find the cumulative sum along the columns. Then output the 2nd (1st index) column but only the first 10 rows. You should get a very recognizable pattern.

In [116]:
x = np.array([[0,1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10,0], [2,3,4,5,6,7,8,9,10,0,1], [3,4,5,6,7,8,9,10,0,1,2],[4,5,6,7,8,9,10,0,1,2,3],[5,6,7,8,9,10,0,1,2,3,4],[6,7,8,9,10,0,1,2,3,4,5],[7,8,9,10,0,1,2,3,4,5,6],[8,9,10,0,1,2,3,4,5,6,7],[9,10,0,1,2,3,4,5,6,7,8],[10,0,1,2,3,4,5,6,7,8,9]])
out = np.cumsum(x)
print(x)
out = np.cumsum(x,axis=1) 
print(out)
out = np.cumsum(out,axis=0) 
print(out)

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10  0]
 [ 2  3  4  5  6  7  8  9 10  0  1]
 [ 3  4  5  6  7  8  9 10  0  1  2]
 [ 4  5  6  7  8  9 10  0  1  2  3]
 [ 5  6  7  8  9 10  0  1  2  3  4]
 [ 6  7  8  9 10  0  1  2  3  4  5]
 [ 7  8  9 10  0  1  2  3  4  5  6]
 [ 8  9 10  0  1  2  3  4  5  6  7]
 [ 9 10  0  1  2  3  4  5  6  7  8]
 [10  0  1  2  3  4  5  6  7  8  9]]
[[ 0  1  3  6 10 15 21 28 36 45 55]
 [ 1  3  6 10 15 21 28 36 45 55 55]
 [ 2  5  9 14 20 27 35 44 54 54 55]
 [ 3  7 12 18 25 33 42 52 52 53 55]
 [ 4  9 15 22 30 39 49 49 50 52 55]
 [ 5 11 18 26 35 45 45 46 48 51 55]
 [ 6 13 21 30 40 40 41 43 46 50 55]
 [ 7 15 24 34 34 35 37 40 44 49 55]
 [ 8 17 27 27 28 30 33 37 42 48 55]
 [ 9 19 19 20 22 25 29 34 40 47 55]
 [10 10 11 13 16 20 25 31 38 46 55]]
[[  0   1   3   6  10  15  21  28  36  45  55]
 [  1   4   9  16  25  36  49  64  81 100 110]
 [  3   9  18  30  45  63  84 108 135 154 165]
 [  6  16  30  48  70  96 126 160 187 207 220]
 [ 10  25  45  70 

In [117]:
out[:-1,1] 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Exercise 7

Using the following string. Turn it into a numpy array where all the letters are their own element.

In [118]:
x = "Life's Good"
np.array(list(x))

array(['L', 'i', 'f', 'e', "'", 's', ' ', 'G', 'o', 'o', 'd'], dtype='<U1')

### Exercise 8

How would we flatten the following array?

In [120]:
x = np.eye(5)
x.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

## Part 3 - Pandas Problems
<hr>

**1.** Create a dataframe using the following:

In [123]:
lst = [['Red',4],['Blue',6],['Green',1],\
       ['Yellow',5],['White',3],['Black',2],]

df = pd.DataFrame(lst)
df

0  1
0     Red  4
1    Blue  6
2   Green  1
3  Yellow  5
4   White  3
5   Black  2

**2.** Create a dataframe using the following:

In [130]:
dct = {'red':4, 'blue':6, 'green':1, 'yellow':5, 'white':3, 'black':2}

df = pd.DataFrame(dct, index = ['color', 'value'], columns = ['a', 'b'])
print(df, "\n")

         a    b
color  NaN  NaN
value  NaN  NaN 



**The following exercises will use the dataset imported below:**


In [131]:
df = pd.DataFrame([[np.nan,'Toyota','Camry',336978, 24765,np.nan],[2019,'Toyota','Corolla',304850, np.nan,4560556],[2019,'Toyota','Supra',np.nan, 35545,102511.78],[2019,np.nan,'Avalon',np.nan ,36480,1012940.16]])
df.columns = ['year', 'make', 'model', 'number sold', 'price', 'revenue (in thousands)']
df

year    make    model  number sold    price  revenue (in thousands)
0     NaN  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 4

Fix the `year` column in the dataframe by replacing missing values with the average value of that column.

In [132]:
df["year"] = df["year"].fillna(df["year"].mean())
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

In [133]:
df["year"] = df["year"].astype('int32')
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                     NaN
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 5

Fix the `'make'` column by replacing the missing value with the value that occurred most frequently (mode).

In [134]:
x = df["make"].mode()[0]
df["make"].fillna(x, inplace = True)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0                     NaN
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 6

Fix the `'revenue (in thousands)'` column by calculating the approximate revenue. Remember that the value of `'revenue'` is in the 1000s.

$$ \textrm{revenue} = \textrm{number sold} * \textrm{price} $$

In [135]:
df["revenue (in thousands)"] = df["revenue (in thousands)"].fillna((df["number sold"]*df["price"])/1000)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 7

Fix the `'price'` column by calculating the approximate price.

$$ \textrm{price} = \frac{\textrm{revenue}}{\textrm{number sold}} $$

In [136]:
df["price"] = df["price"].fillna((df["revenue (in thousands)"]*1000) / df["number sold"])
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 8

Fix the `'number sold'` column by calculating the approximate number of vehicles sold.

$$ \textrm{number sold} = \frac{\textrm{revenue}}{\textrm{price}} $$

In [137]:
df['number sold']= df['number sold'].fillna((df['revenue (in thousands)']*1000) / df['price'])
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019  Toyota    Supra       2884.0  35545.0               102511.78
3  2019  Toyota   Avalon      27767.0  36480.0              1012940.16